spring:
  redis:
    host: localhost
    port: 6379
    timeout: 30000
    jedis:
      pool:
        max-wait: 30000
        max-active: 100
        max-idle: 20
        min-idle: 0

server:
  port: 9936